services:
  warehouse:
    image: postgres:17
    restart: always
    ports:
      - "${MB__DEV__WAREHOUSE_PORT:-7654}:5432"
    volumes:
      - warehouse_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=warehouse_user
      - POSTGRES_PASSWORD=warehouse_password
      - POSTGRES_DB=warehouse
  filestorage:
    image: minio/minio:latest
    restart: always
    volumes:
      - matchbox_store:/data
    command: server --console-address ":9001" /data
    ports:
      - "${MB__DEV__DATASTORE_PORT:-9000}:9000"
      - "${MB__DEV__DATASTORE_CONSOLE_PORT-9001}:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MINIO_ROOT_USER: ${MB__SERVER__DATASTORE__ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${MB__SERVER__DATASTORE__SECRET_ACCESS_KEY}
  api:
    build:
      context: .
      args:
        ENV_FILE: containers.env
        MB_VERSION: ${MB_VERSION-0.0.0dev0}
      dockerfile: src/matchbox/server/Dockerfile
      target: dev
    ports:
      - "${MB__DEV__API_PORT-8000}:8000"
    command: fastapi dev --host 0.0.0.0 src/matchbox/server/api
    depends_on:
      - postgres
      - warehouse
      - filestorage
      - redis
      - worker
    develop:
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: ./src/matchbox
          target: /code/src/matchbox

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "${MB__DEV__POSTGRES_BACKEND_PORT:-5432}:5432"
    volumes:
      - matchbox_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=matchbox
      - POSTGRES_PASSWORD=matchbox_password
      - POSTGRES_USER=matchbox_user
  redis:
    image: redis:8
    restart: always
    ports:
      - "${MB__DEV__REDIS_PORT:-6379}:6379"
  worker:
    build:
      context: .
      dockerfile: src/matchbox/server/Dockerfile
      target: dev
      args:
        ENV_FILE: containers.env
        MB_VERSION: ${MB_VERSION-0.0.0dev0}
    command: celery -A matchbox.server.uploads.celery worker --loglevel=info
    depends_on:
      - postgres
      - filestorage
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
  flower:
    image: mher/flower
    container_name: flower
    ports:
      - "${MB__DEV__FLOWER_PORT:-5555}:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0 
    command: celery flower --broker=${CELERY_BROKER_URL}
    depends_on:
      - redis


volumes:
  warehouse_data:
  matchbox_data:
  matchbox_store:
