"""drop truth_cache from resolution_from.

Revision ID: e06333c2daaf
Revises: a43de8fd3981
Create Date: 2026-02-19 11:18:35.699303

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e06333c2daaf"
down_revision: str | None = "a43de8fd3981"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resolution_from", "truth_cache", schema="mb")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resolution_from",
        sa.Column("truth_cache", sa.SMALLINT(), autoincrement=False, nullable=True),
        schema="mb",
    )
    # ### end Alembic commands ###
