name: Test build

on:
  pull_request:
    branches:
      - main
      - "feature/**"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"

      - run: uv build

      - name: Check version
        run: |
          LATEST_TAG=$(git tag -l | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -n1)
          BUILT_VERSION=$(ls dist/*.whl | head -n1 | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+.*)-py.*/\1/')

          echo "Latest: ${LATEST_TAG#v}, Built: ${BUILT_VERSION}"

          # Use sort -V to compare versions
          if [[ $(printf '%s\n' "${LATEST_TAG#v}" "${BUILT_VERSION}" | sort -V | tail -n1) == "${BUILT_VERSION}" ]]; then
            echo "✅ Version check passed"
          else
            echo "❌ Built version must be >= latest tag"
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist
