name: Documentation (build)
on:
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    permissions:
      pages: write
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with: 
          python-version: 3.11

      - name: Install the project
        run: uv sync --frozen --all-extras --dev

      - name: Build with MkDocs
        run: uv run mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
