name: Unit tests

on:
  pull_request:
    branches:
      - main
      - 'feature/**'
  workflow_dispatch:

jobs:
  run-unit-tests:
    permissions:
      contents: read
    name: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Copy environment variables
        run: cp environments/development.env .env

      - name: Run DBs and API
        run: |
          touch .datadog.env
          LOCAL_USERNAME=github-pipeline docker compose --env-file=environments/server.env up -d --wait --scale datadog-agent=0

      - name: Run pytest
        run: |
          uv run pytest

      - name: Dump docker logs
        if: failure()
        uses: jwalton/gh-docker-logs@v2
